### ISSUE TITLE
Rename variable for `nonce` to be more D&I appropriate 

### ISSUE THREAD

**Issue by jtracey93** [Azure/terraform-provider-modtm#20]
The input variable to the provider of `nonce` has multiple meanings and unfortunately one of those is quite derogatory.

We should consider changing this, even though it would be a breaking change.

References:
- https://dictionary.cambridge.org/dictionary/english/nonce

**Comment by lonegunmanb** [comment]
Thanks for reporting this issue @jtracey93 , this `nonce` comes from "Cryptographic Nonce" and it has been used in bitcoin's protocol for a long time. Do you have any suggestion on the new name since `nonce` stands for:

1. A random integer
2. Should be updated each time we have a new version
3. Should be unique

Thanks in advance!

**Comment by jtracey93** [comment]
How does version_seed go or just seed?
